% automatically generated by wrap
classdef ns1ClassA < handle
  properties
    self = 0
  end
  methods
    function obj = ns1ClassA(varargin)
      if (nargin == 0), obj.self = new_ns1ClassA(0,0); end
      if nargin ==14, new_ns1ClassA(varargin{1},0); end
      if nargin ~= 13 && nargin ~= 14 && obj.self == 0, error('ns1ClassA constructor failed'); end
    end
    function delete(obj)
      if obj.self ~= 0
        new_ns1ClassA(obj.self);
        obj.self = 0;
      end
    end
    function display(obj), obj.print(''); end
    function disp(obj), obj.display; end
  end
end
