// automatically generated by wrap
#include <wrap/matlab.h>
#include <set>
#include <path/to/ns2.h>
#include <path/to/ns2/ClassA.h>
typedef boost::shared_ptr<ns2::ClassA> Shared;
void mexFunction(int nargout, mxArray *out[], int nargin, const mxArray *in[])
{
  checkArguments("memberFunction",nargout,nargin-1,0);
  mxArray* mxh = mxGetProperty(in[0],0,"self");
  Shared* self = *reinterpret_cast<Shared**> (mxGetPr(mxh));
  Shared obj = *self;
  double result = obj->memberFunction();
  out[0] = wrap< double >(result);
}
