// automatically generated by wrap
#include <wrap/matlab.h>
#include <set>
#include <path/to/ns2.h>
#include <path/to/ns2/ClassA.h>
typedef boost::shared_ptr<ns2::ns3::ClassB> SharedClassB;
typedef boost::shared_ptr<ns2::ClassA> Shared;
void mexFunction(int nargout, mxArray *out[], int nargin, const mxArray *in[])
{
  checkArguments("nsReturn",nargout,nargin-1,1);
  mxArray* mxh = mxGetProperty(in[0],0,"self");
  Shared* self = *reinterpret_cast<Shared**> (mxGetPr(mxh));
  Shared obj = *self;
      double q = unwrap< double >(in[1]);
  ns2::ns3::ClassB result = obj->nsReturn(q);
  SharedClassB* ret = new SharedClassB(new ns2::ns3::ClassB(result));
  out[0] = wrap_collect_shared_ptr(ret,"ns2ns3ClassB");
}
