// automatically generated by wrap on 2010-Feb-23
#include <wrap/matlab.h>
#include <Point2.h>
void mexFunction(int nargout, mxArray *out[], int nargin, const mxArray *in[])
{
  checkArguments("new_Point2_",nargout,nargin,0);
  Point2* self = new Point2();
  out[0] = wrap_constructed(self,"Point2");
}
