// automatically generated by wrap
#include <wrap/matlab.h>
#include <folder/path/to/Test.h>
using namespace geometry;
typedef boost::shared_ptr<Test> Shared;

static std::set<Shared*> collector;

void cleanup(void) {
  for(std::set<Shared*>::iterator iter = collector.begin(); iter != collector.end(); ) {
    delete *iter;
    collector.erase(iter++);
  }
}
void mexFunction(int nargout, mxArray *out[], int nargin, const mxArray *in[])
{
  mexAtExit(cleanup);

  const mxArray* input = in[0];
  Shared* self = *(Shared**) mxGetData(input);

  if(self) {
    if(nargin > 1) {
      collector.insert(self);
    }
    else if(collector.erase(self))
      delete self;
  } else {
    int nc = unwrap<int>(in[1]);

    if(nc == 0)
      self = new Shared(new Test());
    if(nc == 1) {
  double a = unwrap< double >(in[2]);
  Matrix b = unwrap< Matrix >(in[3]);
      self = new Shared(new Test(a,b));
    }
    collector.insert(self);
    out[0] = mxCreateNumericMatrix(1, 1, mxUINT32OR64_CLASS, mxREAL);
    *reinterpret_cast<Shared**> (mxGetPr(out[0])) = self;
  }
}
