// automatically generated by wrap on 2011-Dec-06
#include <wrap/matlab.h>
#include <Point3.h>
void mexFunction(int nargout, mxArray *out[], int nargin, const mxArray *in[])
{
  checkArguments("new_Point3_ddd",nargout,nargin,3);
  double x = unwrap< double >(in[0]);
  double y = unwrap< double >(in[1]);
  double z = unwrap< double >(in[2]);
  Point3* self = new Point3(x,y,z);
  out[0] = wrap_constructed(self,"Point3");
}
