// automatically generated by wrap on 2011-Dec-01
#include <wrap/matlab.h>
#include <Test.h>
void mexFunction(int nargout, mxArray *out[], int nargin, const mxArray *in[])
{
  checkArguments("new_Test_b",nargout,nargin,1);
  bool value = unwrap< bool >(in[0]);
  Test* self = new Test(value);
  out[0] = wrap_constructed(self,"Test");
}
