// automatically generated by wrap on 2011-Dec-06
#include <wrap/matlab.h>
#include <Test.h>
void mexFunction(int nargout, mxArray *out[], int nargin, const mxArray *in[])
{
  checkArguments("new_Test_",nargout,nargin,0);
  Test* self = new Test();
  out[0] = wrap_constructed(self,"Test");
}
