// automatically generated by wrap on 2012-Jan-15
#include <wrap/matlab.h>
#include <folder/path/to/Test.h>
using namespace geometry;
void mexFunction(int nargout, mxArray *out[], int nargin, const mxArray *in[])
{
  checkArguments("new_Test_",nargout,nargin,0);
  Test* self = new Test();
  out[0] = wrap_constructed(self,"Test");
}
