// automatically generated by wrap
#include <wrap/matlab.h>
#include <set>
#include <Point3.h>
using namespace geometry;
typedef boost::shared_ptr<Point3> SharedPoint3;
typedef boost::shared_ptr<Point3> Shared;
void mexFunction(int nargout, mxArray *out[], int nargin, const mxArray *in[])
{
  checkArguments("Point3_StaticFunctionRet",nargout,nargin,1);
      double z = unwrap< double >(in[0]);
  Point3 result = Point3::StaticFunctionRet(z);
  SharedPoint3* ret = new SharedPoint3(new Point3(result));
  out[0] = wrap_collect_shared_ptr(ret,"Point3");
}
