% automatically generated by wrap
classdef Point2 < handle
  properties
    ptr_Point2 = 0
  end
  methods
    function obj = Point2(varargin)
      if nargin == 2 && isa(varargin{1}, 'uint64') && varargin{1} == uint64(5139824614673773682)
        my_ptr = varargin{2};
        geometry_wrapper(0, my_ptr);
      elseif nargin == 0
        my_ptr = geometry_wrapper(1);
      elseif nargin == 2 && isa(varargin{1},'double') && isa(varargin{2},'double')
        my_ptr = geometry_wrapper(2, varargin{1}, varargin{2});
      else
        error('Arguments do not match any overload of Point2 constructor');
      end
      obj.ptr_Point2 = my_ptr;
    end

    function delete(obj)
      geometry_wrapper(3, obj.ptr_Point2);
    end

    function display(obj), obj.print(''); end

    function disp(obj), obj.display; end

    function varargout = argChar(this, varargin)
      if length(varargin) == 1 && isa(varargin{1},'char')
        geometry_wrapper(4, this, varargin{:});
      else
        error('Arguments do not match any overload of function Point2.argChar');
      end
    end

    function varargout = argUChar(this, varargin)
      if length(varargin) == 1 && isa(varargin{1},'char')
        geometry_wrapper(5, this, varargin{:});
      else
        error('Arguments do not match any overload of function Point2.argUChar');
      end
    end

    function varargout = dim(this, varargin)
      if length(varargin) == 0
        varargout{1} = geometry_wrapper(6, this, varargin{:});
      else
        error('Arguments do not match any overload of function Point2.dim');
      end
    end

    function varargout = returnChar(this, varargin)
      if length(varargin) == 0
        varargout{1} = geometry_wrapper(7, this, varargin{:});
      else
        error('Arguments do not match any overload of function Point2.returnChar');
      end
    end

    function varargout = vectorConfusion(this, varargin)
      if length(varargin) == 0
        varargout{1} = geometry_wrapper(8, this, varargin{:});
      else
        error('Arguments do not match any overload of function Point2.vectorConfusion');
      end
    end

    function varargout = x(this, varargin)
      if length(varargin) == 0
        varargout{1} = geometry_wrapper(9, this, varargin{:});
      else
        error('Arguments do not match any overload of function Point2.x');
      end
    end

    function varargout = y(this, varargin)
      if length(varargin) == 0
        varargout{1} = geometry_wrapper(10, this, varargin{:});
      else
        error('Arguments do not match any overload of function Point2.y');
      end
    end

  end

  methods(Static = true)
  end
end
