// automatically generated by wrap on 2011-Dec-01
#include <wrap/matlab.h>
#include <Point3.h>
void mexFunction(int nargout, mxArray *out[], int nargin, const mxArray *in[])
{
  checkArguments("Point3_StaticFunction",nargout,nargin,0);
  double result = Point3::StaticFunction();
  out[0] = wrap< double >(result);
}
