// automatically generated by wrap on 2011-Dec-06
#include <wrap/matlab.h>
#include <Point3.h>
void mexFunction(int nargout, mxArray *out[], int nargin, const mxArray *in[])
{
  checkArguments("Point3_StaticFunctionRet",nargout,nargin,0);
  Point3 result = Point3::StaticFunctionRet();
  out[0] = wrap_shared_ptr(make_shared< Point3 >(result),"Point3");
}
