// automatically generated by wrap on 2011-Dec-09
#include <wrap/matlab.h>
#include <Point3.h>
using namespace geometry;
void mexFunction(int nargout, mxArray *out[], int nargin, const mxArray *in[])
{
  checkArguments("Point3_staticFunction",nargout,nargin,0);
  double result = Point3::staticFunction();
  out[0] = wrap< double >(result);
}
