// automatically generated by wrap
#include <wrap/matlab.h>
#include <Point3.h>
using namespace geometry;
typedef boost::shared_ptr<double> Shareddouble;
typedef boost::shared_ptr<Point3> Shared;
void mexFunction(int nargout, mxArray *out[], int nargin, const mxArray *in[])
{
  checkArguments("Point3_staticFunction",nargout,nargin,0);
  double result = Point3::staticFunction();
  out[0] = wrap< double >(result);
}
