% automatically generated by wrap
classdef Test < handle
  properties
    self = 0
  end
  methods
    function obj = Test(varargin)
      if nargin == 2 && isa(varargin{1}, 'uint64') && varargin{1} == uint64(5139824614673773682)
        obj.self = varargin{2};
        geometry_wrapper(obj.self);
      elseif nargin == 0
        obj.self = geometry_wrapper(18);
      elseif nargin == 2 && isa(varargin{1},'double') && isa(varargin{2},'double')
        obj.self = geometry_wrapper(19,varargin{1},varargin{2});
      else
        error('Arguments do not match any overload of Test constructor');
      end
    end

    function delete(obj)
      geometry_wrapper(20, obj.self);
    end

    function display(obj), obj.print(''); end

    function disp(obj), obj.display; end

    function varargout = arg_EigenConstRef(self, varargin)
      if length(varargin) == 1 && isa(varargin{1},'double')
        geometry_wrapper(21, self, varargin{:});
      else
        error('Arguments do not match any overload of function Test.arg_EigenConstRef');
      end
    end

    function varargout = create_MixedPtrs(self, varargin)
      if length(varargin) == 0
        [ varargout{1} varargout{2} ] = geometry_wrapper(22, self, varargin{:});
      else
        error('Arguments do not match any overload of function Test.create_MixedPtrs');
      end
    end

    function varargout = create_ptrs(self, varargin)
      if length(varargin) == 0
        [ varargout{1} varargout{2} ] = geometry_wrapper(23, self, varargin{:});
      else
        error('Arguments do not match any overload of function Test.create_ptrs');
      end
    end

    function varargout = print(self, varargin)
      if length(varargin) == 0
        geometry_wrapper(24, self, varargin{:});
      else
        error('Arguments do not match any overload of function Test.print');
      end
    end

    function varargout = return_Point2Ptr(self, varargin)
      if length(varargin) == 1 && isa(varargin{1},'logical')
        varargout{1} = geometry_wrapper(25, self, varargin{:});
      else
        error('Arguments do not match any overload of function Test.return_Point2Ptr');
      end
    end

    function varargout = return_Test(self, varargin)
      if length(varargin) == 1 && isa(varargin{1},'Test')
        varargout{1} = geometry_wrapper(26, self, varargin{:});
      else
        error('Arguments do not match any overload of function Test.return_Test');
      end
    end

    function varargout = return_TestPtr(self, varargin)
      if length(varargin) == 1 && isa(varargin{1},'Test')
        varargout{1} = geometry_wrapper(27, self, varargin{:});
      else
        error('Arguments do not match any overload of function Test.return_TestPtr');
      end
    end

    function varargout = return_bool(self, varargin)
      if length(varargin) == 1 && isa(varargin{1},'logical')
        varargout{1} = geometry_wrapper(28, self, varargin{:});
      else
        error('Arguments do not match any overload of function Test.return_bool');
      end
    end

    function varargout = return_double(self, varargin)
      if length(varargin) == 1 && isa(varargin{1},'double')
        varargout{1} = geometry_wrapper(29, self, varargin{:});
      else
        error('Arguments do not match any overload of function Test.return_double');
      end
    end

    function varargout = return_field(self, varargin)
      if length(varargin) == 1 && isa(varargin{1},'Test')
        varargout{1} = geometry_wrapper(30, self, varargin{:});
      else
        error('Arguments do not match any overload of function Test.return_field');
      end
    end

    function varargout = return_int(self, varargin)
      if length(varargin) == 1 && isa(varargin{1},'numeric')
        varargout{1} = geometry_wrapper(31, self, varargin{:});
      else
        error('Arguments do not match any overload of function Test.return_int');
      end
    end

    function varargout = return_matrix1(self, varargin)
      if length(varargin) == 1 && isa(varargin{1},'double')
        varargout{1} = geometry_wrapper(32, self, varargin{:});
      else
        error('Arguments do not match any overload of function Test.return_matrix1');
      end
    end

    function varargout = return_matrix2(self, varargin)
      if length(varargin) == 1 && isa(varargin{1},'double')
        varargout{1} = geometry_wrapper(33, self, varargin{:});
      else
        error('Arguments do not match any overload of function Test.return_matrix2');
      end
    end

    function varargout = return_pair(self, varargin)
      if length(varargin) == 2 && isa(varargin{1},'double') && isa(varargin{2},'double')
        [ varargout{1} varargout{2} ] = geometry_wrapper(34, self, varargin{:});
      else
        error('Arguments do not match any overload of function Test.return_pair');
      end
    end

    function varargout = return_ptrs(self, varargin)
      if length(varargin) == 2 && isa(varargin{1},'Test') && isa(varargin{2},'Test')
        [ varargout{1} varargout{2} ] = geometry_wrapper(35, self, varargin{:});
      else
        error('Arguments do not match any overload of function Test.return_ptrs');
      end
    end

    function varargout = return_size_t(self, varargin)
      if length(varargin) == 1 && isa(varargin{1},'numeric')
        varargout{1} = geometry_wrapper(36, self, varargin{:});
      else
        error('Arguments do not match any overload of function Test.return_size_t');
      end
    end

    function varargout = return_string(self, varargin)
      if length(varargin) == 1 && isa(varargin{1},'char')
        varargout{1} = geometry_wrapper(37, self, varargin{:});
      else
        error('Arguments do not match any overload of function Test.return_string');
      end
    end

    function varargout = return_vector1(self, varargin)
      if length(varargin) == 1 && isa(varargin{1},'double')
        varargout{1} = geometry_wrapper(38, self, varargin{:});
      else
        error('Arguments do not match any overload of function Test.return_vector1');
      end
    end

    function varargout = return_vector2(self, varargin)
      if length(varargin) == 1 && isa(varargin{1},'double')
        varargout{1} = geometry_wrapper(39, self, varargin{:});
      else
        error('Arguments do not match any overload of function Test.return_vector2');
      end
    end

  end

  methods(Static = true)
  end
end
