% automatically generated by wrap on 2009-Dec-11
echo on

toolboxpath = '/Users/dellaert/toolbox/gtsam'
addpath(toolboxpath);

% cd(toolboxpath)
% mex -I/opt/local/include/ -I/Users/dellaert/include -I/Users/dellaert/include/gtsam -L/Users/dellaert/lib -lgtsam new_Pose2_.cpp
% mex -I/opt/local/include/ -I/Users/dellaert/include -I/Users/dellaert/include/gtsam -L/Users/dellaert/lib -lgtsam new_Pose2_P.cpp
% mex -I/opt/local/include/ -I/Users/dellaert/include -I/Users/dellaert/include/gtsam -L/Users/dellaert/lib -lgtsam new_Pose2_ddd.cpp
% 
% cd @Pose2
% mex -I/opt/local/include/ -I/Users/dellaert/include -I/Users/dellaert/include/gtsam -L/Users/dellaert/lib -lgtsam print.cpp
% mex -I/opt/local/include/ -I/Users/dellaert/include -I/Users/dellaert/include/gtsam -L/Users/dellaert/lib -lgtsam equals.cpp
% mex -I/opt/local/include/ -I/Users/dellaert/include -I/Users/dellaert/include/gtsam -L/Users/dellaert/lib -lgtsam x.cpp
% mex -I/opt/local/include/ -I/Users/dellaert/include -I/Users/dellaert/include/gtsam -L/Users/dellaert/lib -lgtsam y.cpp
% mex -I/opt/local/include/ -I/Users/dellaert/include -I/Users/dellaert/include/gtsam -L/Users/dellaert/lib -lgtsam theta.cpp
% mex -I/opt/local/include/ -I/Users/dellaert/include -I/Users/dellaert/include/gtsam -L/Users/dellaert/lib -lgtsam dim.cpp
% mex -I/opt/local/include/ -I/Users/dellaert/include -I/Users/dellaert/include/gtsam -L/Users/dellaert/lib -lgtsam exmap.cpp
% mex -I/opt/local/include/ -I/Users/dellaert/include -I/Users/dellaert/include/gtsam -L/Users/dellaert/lib -lgtsam vector.cpp
% mex -I/opt/local/include/ -I/Users/dellaert/include -I/Users/dellaert/include/gtsam -L/Users/dellaert/lib -lgtsam rotate.cpp

cd(toolboxpath)
mex -I/opt/local/include/ -I/Users/dellaert/include -I/Users/dellaert/include/gtsam -L/Users/dellaert/lib -lgtsam new_Pose2Config_.cpp

cd @Pose2Config
mex -I/opt/local/include/ -I/Users/dellaert/include -I/Users/dellaert/include/gtsam -L/Users/dellaert/lib -lgtsam get.cpp
mex -I/opt/local/include/ -I/Users/dellaert/include -I/Users/dellaert/include/gtsam -L/Users/dellaert/lib -lgtsam insert.cpp
% mex -I/opt/local/include/ -I/Users/dellaert/include -I/Users/dellaert/include/gtsam -L/Users/dellaert/lib -lgtsam print.cpp

cd(toolboxpath)
mex -I/opt/local/include/ -I/Users/dellaert/include -I/Users/dellaert/include/gtsam -L/Users/dellaert/lib -lgtsam new_Pose2Factor_ssPM.cpp

cd @Pose2Factor
mex -I/opt/local/include/ -I/Users/dellaert/include -I/Users/dellaert/include/gtsam -L/Users/dellaert/lib -lgtsam print.cpp
mex -I/opt/local/include/ -I/Users/dellaert/include -I/Users/dellaert/include/gtsam -L/Users/dellaert/lib -lgtsam equals.cpp
mex -I/opt/local/include/ -I/Users/dellaert/include -I/Users/dellaert/include/gtsam -L/Users/dellaert/lib -lgtsam error.cpp
mex -I/opt/local/include/ -I/Users/dellaert/include -I/Users/dellaert/include/gtsam -L/Users/dellaert/lib -lgtsam size.cpp
mex -I/opt/local/include/ -I/Users/dellaert/include -I/Users/dellaert/include/gtsam -L/Users/dellaert/lib -lgtsam linearize.cpp

cd(toolboxpath)
mex -I/opt/local/include/ -I/Users/dellaert/include -I/Users/dellaert/include/gtsam -L/Users/dellaert/lib -lgtsam new_Pose2Graph_.cpp

cd @Pose2Graph
mex -I/opt/local/include/ -I/Users/dellaert/include -I/Users/dellaert/include/gtsam -L/Users/dellaert/lib -lgtsam print.cpp
mex -I/opt/local/include/ -I/Users/dellaert/include -I/Users/dellaert/include/gtsam -L/Users/dellaert/lib -lgtsam equals.cpp
mex -I/opt/local/include/ -I/Users/dellaert/include -I/Users/dellaert/include/gtsam -L/Users/dellaert/lib -lgtsam linearize_.cpp
mex -I/opt/local/include/ -I/Users/dellaert/include -I/Users/dellaert/include/gtsam -L/Users/dellaert/lib -lgtsam push_back.cpp
mex -I/opt/local/include/ -I/Users/dellaert/include -I/Users/dellaert/include/gtsam -L/Users/dellaert/lib -lgtsam getOrdering_.cpp

cd(toolboxpath)

echo off
