# This image connects to the host X-server via VNC to provide a Graphical User Interface for interaction.

# base image off gtsam image
ARG GTSAM_TAG=4.2.0-tbb-ON-python-ON_22.04
FROM docker.io/borglab/gtsam:${GTSAM_TAG}

RUN apt-get update && apt-get install -y --no-install-recommends \
# Things needed to get a python GUI
    python3-tk \
    python3-matplotlib \
# Install a VNC X-server, Frame buffer, and windows manager
    x11vnc \
    xvfb \
    fluxbox \
# Finally, install wmctrl needed for bootstrap script
    wmctrl \
    rm -rf /var/lib/apt/lists/*

COPY bootstrap.sh /
CMD ["/bootstrap.sh"]
