/* Generated by Cython 0.25.2 */

#ifndef __PYX_HAVE_API__eigency__conversions
#define __PYX_HAVE_API__eigency__conversions
#include "Python.h"

static PyArrayObject *(*__pyx_api_f_7eigency_11conversions_ndarray_double_C)(double *, long, long, long, long) = 0;
#define ndarray_double_C __pyx_api_f_7eigency_11conversions_ndarray_double_C
static PyArrayObject *(*__pyx_api_f_7eigency_11conversions_ndarray_double_F)(double *, long, long, long, long) = 0;
#define ndarray_double_F __pyx_api_f_7eigency_11conversions_ndarray_double_F
static PyArrayObject *(*__pyx_api_f_7eigency_11conversions_ndarray_copy_double_C)(double const *, long, long, long, long) = 0;
#define ndarray_copy_double_C __pyx_api_f_7eigency_11conversions_ndarray_copy_double_C
static PyArrayObject *(*__pyx_api_f_7eigency_11conversions_ndarray_copy_double_F)(double const *, long, long, long, long) = 0;
#define ndarray_copy_double_F __pyx_api_f_7eigency_11conversions_ndarray_copy_double_F
static PyArrayObject *(*__pyx_api_f_7eigency_11conversions_ndarray_float_C)(float *, long, long, long, long) = 0;
#define ndarray_float_C __pyx_api_f_7eigency_11conversions_ndarray_float_C
static PyArrayObject *(*__pyx_api_f_7eigency_11conversions_ndarray_float_F)(float *, long, long, long, long) = 0;
#define ndarray_float_F __pyx_api_f_7eigency_11conversions_ndarray_float_F
static PyArrayObject *(*__pyx_api_f_7eigency_11conversions_ndarray_copy_float_C)(float const *, long, long, long, long) = 0;
#define ndarray_copy_float_C __pyx_api_f_7eigency_11conversions_ndarray_copy_float_C
static PyArrayObject *(*__pyx_api_f_7eigency_11conversions_ndarray_copy_float_F)(float const *, long, long, long, long) = 0;
#define ndarray_copy_float_F __pyx_api_f_7eigency_11conversions_ndarray_copy_float_F
static PyArrayObject *(*__pyx_api_f_7eigency_11conversions_ndarray_long_C)(long *, long, long, long, long) = 0;
#define ndarray_long_C __pyx_api_f_7eigency_11conversions_ndarray_long_C
static PyArrayObject *(*__pyx_api_f_7eigency_11conversions_ndarray_long_F)(long *, long, long, long, long) = 0;
#define ndarray_long_F __pyx_api_f_7eigency_11conversions_ndarray_long_F
static PyArrayObject *(*__pyx_api_f_7eigency_11conversions_ndarray_copy_long_C)(long const *, long, long, long, long) = 0;
#define ndarray_copy_long_C __pyx_api_f_7eigency_11conversions_ndarray_copy_long_C
static PyArrayObject *(*__pyx_api_f_7eigency_11conversions_ndarray_copy_long_F)(long const *, long, long, long, long) = 0;
#define ndarray_copy_long_F __pyx_api_f_7eigency_11conversions_ndarray_copy_long_F
static PyArrayObject *(*__pyx_api_f_7eigency_11conversions_ndarray_ulong_C)(unsigned long *, long, long, long, long) = 0;
#define ndarray_ulong_C __pyx_api_f_7eigency_11conversions_ndarray_ulong_C
static PyArrayObject *(*__pyx_api_f_7eigency_11conversions_ndarray_ulong_F)(unsigned long *, long, long, long, long) = 0;
#define ndarray_ulong_F __pyx_api_f_7eigency_11conversions_ndarray_ulong_F
static PyArrayObject *(*__pyx_api_f_7eigency_11conversions_ndarray_copy_ulong_C)(unsigned long const *, long, long, long, long) = 0;
#define ndarray_copy_ulong_C __pyx_api_f_7eigency_11conversions_ndarray_copy_ulong_C
static PyArrayObject *(*__pyx_api_f_7eigency_11conversions_ndarray_copy_ulong_F)(unsigned long const *, long, long, long, long) = 0;
#define ndarray_copy_ulong_F __pyx_api_f_7eigency_11conversions_ndarray_copy_ulong_F
static PyArrayObject *(*__pyx_api_f_7eigency_11conversions_ndarray_int_C)(int *, long, long, long, long) = 0;
#define ndarray_int_C __pyx_api_f_7eigency_11conversions_ndarray_int_C
static PyArrayObject *(*__pyx_api_f_7eigency_11conversions_ndarray_int_F)(int *, long, long, long, long) = 0;
#define ndarray_int_F __pyx_api_f_7eigency_11conversions_ndarray_int_F
static PyArrayObject *(*__pyx_api_f_7eigency_11conversions_ndarray_copy_int_C)(int const *, long, long, long, long) = 0;
#define ndarray_copy_int_C __pyx_api_f_7eigency_11conversions_ndarray_copy_int_C
static PyArrayObject *(*__pyx_api_f_7eigency_11conversions_ndarray_copy_int_F)(int const *, long, long, long, long) = 0;
#define ndarray_copy_int_F __pyx_api_f_7eigency_11conversions_ndarray_copy_int_F
static PyArrayObject *(*__pyx_api_f_7eigency_11conversions_ndarray_uint_C)(unsigned int *, long, long, long, long) = 0;
#define ndarray_uint_C __pyx_api_f_7eigency_11conversions_ndarray_uint_C
static PyArrayObject *(*__pyx_api_f_7eigency_11conversions_ndarray_uint_F)(unsigned int *, long, long, long, long) = 0;
#define ndarray_uint_F __pyx_api_f_7eigency_11conversions_ndarray_uint_F
static PyArrayObject *(*__pyx_api_f_7eigency_11conversions_ndarray_copy_uint_C)(unsigned int const *, long, long, long, long) = 0;
#define ndarray_copy_uint_C __pyx_api_f_7eigency_11conversions_ndarray_copy_uint_C
static PyArrayObject *(*__pyx_api_f_7eigency_11conversions_ndarray_copy_uint_F)(unsigned int const *, long, long, long, long) = 0;
#define ndarray_copy_uint_F __pyx_api_f_7eigency_11conversions_ndarray_copy_uint_F
static PyArrayObject *(*__pyx_api_f_7eigency_11conversions_ndarray_short_C)(short *, long, long, long, long) = 0;
#define ndarray_short_C __pyx_api_f_7eigency_11conversions_ndarray_short_C
static PyArrayObject *(*__pyx_api_f_7eigency_11conversions_ndarray_short_F)(short *, long, long, long, long) = 0;
#define ndarray_short_F __pyx_api_f_7eigency_11conversions_ndarray_short_F
static PyArrayObject *(*__pyx_api_f_7eigency_11conversions_ndarray_copy_short_C)(short const *, long, long, long, long) = 0;
#define ndarray_copy_short_C __pyx_api_f_7eigency_11conversions_ndarray_copy_short_C
static PyArrayObject *(*__pyx_api_f_7eigency_11conversions_ndarray_copy_short_F)(short const *, long, long, long, long) = 0;
#define ndarray_copy_short_F __pyx_api_f_7eigency_11conversions_ndarray_copy_short_F
static PyArrayObject *(*__pyx_api_f_7eigency_11conversions_ndarray_ushort_C)(unsigned short *, long, long, long, long) = 0;
#define ndarray_ushort_C __pyx_api_f_7eigency_11conversions_ndarray_ushort_C
static PyArrayObject *(*__pyx_api_f_7eigency_11conversions_ndarray_ushort_F)(unsigned short *, long, long, long, long) = 0;
#define ndarray_ushort_F __pyx_api_f_7eigency_11conversions_ndarray_ushort_F
static PyArrayObject *(*__pyx_api_f_7eigency_11conversions_ndarray_copy_ushort_C)(unsigned short const *, long, long, long, long) = 0;
#define ndarray_copy_ushort_C __pyx_api_f_7eigency_11conversions_ndarray_copy_ushort_C
static PyArrayObject *(*__pyx_api_f_7eigency_11conversions_ndarray_copy_ushort_F)(unsigned short const *, long, long, long, long) = 0;
#define ndarray_copy_ushort_F __pyx_api_f_7eigency_11conversions_ndarray_copy_ushort_F
static PyArrayObject *(*__pyx_api_f_7eigency_11conversions_ndarray_schar_C)(signed char *, long, long, long, long) = 0;
#define ndarray_schar_C __pyx_api_f_7eigency_11conversions_ndarray_schar_C
static PyArrayObject *(*__pyx_api_f_7eigency_11conversions_ndarray_schar_F)(signed char *, long, long, long, long) = 0;
#define ndarray_schar_F __pyx_api_f_7eigency_11conversions_ndarray_schar_F
static PyArrayObject *(*__pyx_api_f_7eigency_11conversions_ndarray_copy_schar_C)(signed char const *, long, long, long, long) = 0;
#define ndarray_copy_schar_C __pyx_api_f_7eigency_11conversions_ndarray_copy_schar_C
static PyArrayObject *(*__pyx_api_f_7eigency_11conversions_ndarray_copy_schar_F)(signed char const *, long, long, long, long) = 0;
#define ndarray_copy_schar_F __pyx_api_f_7eigency_11conversions_ndarray_copy_schar_F
static PyArrayObject *(*__pyx_api_f_7eigency_11conversions_ndarray_uchar_C)(unsigned char *, long, long, long, long) = 0;
#define ndarray_uchar_C __pyx_api_f_7eigency_11conversions_ndarray_uchar_C
static PyArrayObject *(*__pyx_api_f_7eigency_11conversions_ndarray_uchar_F)(unsigned char *, long, long, long, long) = 0;
#define ndarray_uchar_F __pyx_api_f_7eigency_11conversions_ndarray_uchar_F
static PyArrayObject *(*__pyx_api_f_7eigency_11conversions_ndarray_copy_uchar_C)(unsigned char const *, long, long, long, long) = 0;
#define ndarray_copy_uchar_C __pyx_api_f_7eigency_11conversions_ndarray_copy_uchar_C
static PyArrayObject *(*__pyx_api_f_7eigency_11conversions_ndarray_copy_uchar_F)(unsigned char const *, long, long, long, long) = 0;
#define ndarray_copy_uchar_F __pyx_api_f_7eigency_11conversions_ndarray_copy_uchar_F
static PyArrayObject *(*__pyx_api_f_7eigency_11conversions_ndarray_complex_double_C)(__pyx_t_double_complex *, long, long, long, long) = 0;
#define ndarray_complex_double_C __pyx_api_f_7eigency_11conversions_ndarray_complex_double_C
static PyArrayObject *(*__pyx_api_f_7eigency_11conversions_ndarray_complex_double_F)(__pyx_t_double_complex *, long, long, long, long) = 0;
#define ndarray_complex_double_F __pyx_api_f_7eigency_11conversions_ndarray_complex_double_F
static PyArrayObject *(*__pyx_api_f_7eigency_11conversions_ndarray_copy_complex_double_C)(__pyx_t_double_complex const *, long, long, long, long) = 0;
#define ndarray_copy_complex_double_C __pyx_api_f_7eigency_11conversions_ndarray_copy_complex_double_C
static PyArrayObject *(*__pyx_api_f_7eigency_11conversions_ndarray_copy_complex_double_F)(__pyx_t_double_complex const *, long, long, long, long) = 0;
#define ndarray_copy_complex_double_F __pyx_api_f_7eigency_11conversions_ndarray_copy_complex_double_F
static PyArrayObject *(*__pyx_api_f_7eigency_11conversions_ndarray_complex_float_C)(__pyx_t_float_complex *, long, long, long, long) = 0;
#define ndarray_complex_float_C __pyx_api_f_7eigency_11conversions_ndarray_complex_float_C
static PyArrayObject *(*__pyx_api_f_7eigency_11conversions_ndarray_complex_float_F)(__pyx_t_float_complex *, long, long, long, long) = 0;
#define ndarray_complex_float_F __pyx_api_f_7eigency_11conversions_ndarray_complex_float_F
static PyArrayObject *(*__pyx_api_f_7eigency_11conversions_ndarray_copy_complex_float_C)(__pyx_t_float_complex const *, long, long, long, long) = 0;
#define ndarray_copy_complex_float_C __pyx_api_f_7eigency_11conversions_ndarray_copy_complex_float_C
static PyArrayObject *(*__pyx_api_f_7eigency_11conversions_ndarray_copy_complex_float_F)(__pyx_t_float_complex const *, long, long, long, long) = 0;
#define ndarray_copy_complex_float_F __pyx_api_f_7eigency_11conversions_ndarray_copy_complex_float_F
#if !defined(__Pyx_PyIdentifier_FromString)
#if PY_MAJOR_VERSION < 3
  #define __Pyx_PyIdentifier_FromString(s) PyString_FromString(s)
#else
  #define __Pyx_PyIdentifier_FromString(s) PyUnicode_FromString(s)
#endif
#endif

#ifndef __PYX_HAVE_RT_ImportModule
#define __PYX_HAVE_RT_ImportModule
static PyObject *__Pyx_ImportModule(const char *name) {
    PyObject *py_name = 0;
    PyObject *py_module = 0;
    py_name = __Pyx_PyIdentifier_FromString(name);
    if (!py_name)
        goto bad;
    py_module = PyImport_Import(py_name);
    Py_DECREF(py_name);
    return py_module;
bad:
    Py_XDECREF(py_name);
    return 0;
}
#endif

#ifndef __PYX_HAVE_RT_ImportFunction
#define __PYX_HAVE_RT_ImportFunction
static int __Pyx_ImportFunction(PyObject *module, const char *funcname, void (**f)(void), const char *sig) {
    PyObject *d = 0;
    PyObject *cobj = 0;
    union {
        void (*fp)(void);
        void *p;
    } tmp;
    d = PyObject_GetAttrString(module, (char *)"__pyx_capi__");
    if (!d)
        goto bad;
    cobj = PyDict_GetItemString(d, funcname);
    if (!cobj) {
        PyErr_Format(PyExc_ImportError,
            "%.200s does not export expected C function %.200s",
                PyModule_GetName(module), funcname);
        goto bad;
    }
#if PY_VERSION_HEX >= 0x02070000
    if (!PyCapsule_IsValid(cobj, sig)) {
        PyErr_Format(PyExc_TypeError,
            "C function %.200s.%.200s has wrong signature (expected %.500s, got %.500s)",
             PyModule_GetName(module), funcname, sig, PyCapsule_GetName(cobj));
        goto bad;
    }
    tmp.p = PyCapsule_GetPointer(cobj, sig);
#else
    {const char *desc, *s1, *s2;
    desc = (const char *)PyCObject_GetDesc(cobj);
    if (!desc)
        goto bad;
    s1 = desc; s2 = sig;
    while (*s1 != '\0' && *s1 == *s2) { s1++; s2++; }
    if (*s1 != *s2) {
        PyErr_Format(PyExc_TypeError,
            "C function %.200s.%.200s has wrong signature (expected %.500s, got %.500s)",
             PyModule_GetName(module), funcname, sig, desc);
        goto bad;
    }
    tmp.p = PyCObject_AsVoidPtr(cobj);}
#endif
    *f = tmp.fp;
    if (!(*f))
        goto bad;
    Py_DECREF(d);
    return 0;
bad:
    Py_XDECREF(d);
    return -1;
}
#endif


static int import_eigency__conversions(void) {
  PyObject *module = 0;
  module = __Pyx_ImportModule("eigency.conversions");
  if (!module) goto bad;
  if (__Pyx_ImportFunction(module, "ndarray_double_C", (void (**)(void))&__pyx_api_f_7eigency_11conversions_ndarray_double_C, "PyArrayObject *(double *, long, long, long, long)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "ndarray_double_F", (void (**)(void))&__pyx_api_f_7eigency_11conversions_ndarray_double_F, "PyArrayObject *(double *, long, long, long, long)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "ndarray_copy_double_C", (void (**)(void))&__pyx_api_f_7eigency_11conversions_ndarray_copy_double_C, "PyArrayObject *(double const *, long, long, long, long)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "ndarray_copy_double_F", (void (**)(void))&__pyx_api_f_7eigency_11conversions_ndarray_copy_double_F, "PyArrayObject *(double const *, long, long, long, long)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "ndarray_float_C", (void (**)(void))&__pyx_api_f_7eigency_11conversions_ndarray_float_C, "PyArrayObject *(float *, long, long, long, long)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "ndarray_float_F", (void (**)(void))&__pyx_api_f_7eigency_11conversions_ndarray_float_F, "PyArrayObject *(float *, long, long, long, long)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "ndarray_copy_float_C", (void (**)(void))&__pyx_api_f_7eigency_11conversions_ndarray_copy_float_C, "PyArrayObject *(float const *, long, long, long, long)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "ndarray_copy_float_F", (void (**)(void))&__pyx_api_f_7eigency_11conversions_ndarray_copy_float_F, "PyArrayObject *(float const *, long, long, long, long)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "ndarray_long_C", (void (**)(void))&__pyx_api_f_7eigency_11conversions_ndarray_long_C, "PyArrayObject *(long *, long, long, long, long)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "ndarray_long_F", (void (**)(void))&__pyx_api_f_7eigency_11conversions_ndarray_long_F, "PyArrayObject *(long *, long, long, long, long)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "ndarray_copy_long_C", (void (**)(void))&__pyx_api_f_7eigency_11conversions_ndarray_copy_long_C, "PyArrayObject *(long const *, long, long, long, long)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "ndarray_copy_long_F", (void (**)(void))&__pyx_api_f_7eigency_11conversions_ndarray_copy_long_F, "PyArrayObject *(long const *, long, long, long, long)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "ndarray_ulong_C", (void (**)(void))&__pyx_api_f_7eigency_11conversions_ndarray_ulong_C, "PyArrayObject *(unsigned long *, long, long, long, long)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "ndarray_ulong_F", (void (**)(void))&__pyx_api_f_7eigency_11conversions_ndarray_ulong_F, "PyArrayObject *(unsigned long *, long, long, long, long)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "ndarray_copy_ulong_C", (void (**)(void))&__pyx_api_f_7eigency_11conversions_ndarray_copy_ulong_C, "PyArrayObject *(unsigned long const *, long, long, long, long)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "ndarray_copy_ulong_F", (void (**)(void))&__pyx_api_f_7eigency_11conversions_ndarray_copy_ulong_F, "PyArrayObject *(unsigned long const *, long, long, long, long)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "ndarray_int_C", (void (**)(void))&__pyx_api_f_7eigency_11conversions_ndarray_int_C, "PyArrayObject *(int *, long, long, long, long)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "ndarray_int_F", (void (**)(void))&__pyx_api_f_7eigency_11conversions_ndarray_int_F, "PyArrayObject *(int *, long, long, long, long)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "ndarray_copy_int_C", (void (**)(void))&__pyx_api_f_7eigency_11conversions_ndarray_copy_int_C, "PyArrayObject *(int const *, long, long, long, long)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "ndarray_copy_int_F", (void (**)(void))&__pyx_api_f_7eigency_11conversions_ndarray_copy_int_F, "PyArrayObject *(int const *, long, long, long, long)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "ndarray_uint_C", (void (**)(void))&__pyx_api_f_7eigency_11conversions_ndarray_uint_C, "PyArrayObject *(unsigned int *, long, long, long, long)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "ndarray_uint_F", (void (**)(void))&__pyx_api_f_7eigency_11conversions_ndarray_uint_F, "PyArrayObject *(unsigned int *, long, long, long, long)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "ndarray_copy_uint_C", (void (**)(void))&__pyx_api_f_7eigency_11conversions_ndarray_copy_uint_C, "PyArrayObject *(unsigned int const *, long, long, long, long)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "ndarray_copy_uint_F", (void (**)(void))&__pyx_api_f_7eigency_11conversions_ndarray_copy_uint_F, "PyArrayObject *(unsigned int const *, long, long, long, long)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "ndarray_short_C", (void (**)(void))&__pyx_api_f_7eigency_11conversions_ndarray_short_C, "PyArrayObject *(short *, long, long, long, long)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "ndarray_short_F", (void (**)(void))&__pyx_api_f_7eigency_11conversions_ndarray_short_F, "PyArrayObject *(short *, long, long, long, long)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "ndarray_copy_short_C", (void (**)(void))&__pyx_api_f_7eigency_11conversions_ndarray_copy_short_C, "PyArrayObject *(short const *, long, long, long, long)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "ndarray_copy_short_F", (void (**)(void))&__pyx_api_f_7eigency_11conversions_ndarray_copy_short_F, "PyArrayObject *(short const *, long, long, long, long)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "ndarray_ushort_C", (void (**)(void))&__pyx_api_f_7eigency_11conversions_ndarray_ushort_C, "PyArrayObject *(unsigned short *, long, long, long, long)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "ndarray_ushort_F", (void (**)(void))&__pyx_api_f_7eigency_11conversions_ndarray_ushort_F, "PyArrayObject *(unsigned short *, long, long, long, long)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "ndarray_copy_ushort_C", (void (**)(void))&__pyx_api_f_7eigency_11conversions_ndarray_copy_ushort_C, "PyArrayObject *(unsigned short const *, long, long, long, long)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "ndarray_copy_ushort_F", (void (**)(void))&__pyx_api_f_7eigency_11conversions_ndarray_copy_ushort_F, "PyArrayObject *(unsigned short const *, long, long, long, long)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "ndarray_schar_C", (void (**)(void))&__pyx_api_f_7eigency_11conversions_ndarray_schar_C, "PyArrayObject *(signed char *, long, long, long, long)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "ndarray_schar_F", (void (**)(void))&__pyx_api_f_7eigency_11conversions_ndarray_schar_F, "PyArrayObject *(signed char *, long, long, long, long)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "ndarray_copy_schar_C", (void (**)(void))&__pyx_api_f_7eigency_11conversions_ndarray_copy_schar_C, "PyArrayObject *(signed char const *, long, long, long, long)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "ndarray_copy_schar_F", (void (**)(void))&__pyx_api_f_7eigency_11conversions_ndarray_copy_schar_F, "PyArrayObject *(signed char const *, long, long, long, long)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "ndarray_uchar_C", (void (**)(void))&__pyx_api_f_7eigency_11conversions_ndarray_uchar_C, "PyArrayObject *(unsigned char *, long, long, long, long)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "ndarray_uchar_F", (void (**)(void))&__pyx_api_f_7eigency_11conversions_ndarray_uchar_F, "PyArrayObject *(unsigned char *, long, long, long, long)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "ndarray_copy_uchar_C", (void (**)(void))&__pyx_api_f_7eigency_11conversions_ndarray_copy_uchar_C, "PyArrayObject *(unsigned char const *, long, long, long, long)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "ndarray_copy_uchar_F", (void (**)(void))&__pyx_api_f_7eigency_11conversions_ndarray_copy_uchar_F, "PyArrayObject *(unsigned char const *, long, long, long, long)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "ndarray_complex_double_C", (void (**)(void))&__pyx_api_f_7eigency_11conversions_ndarray_complex_double_C, "PyArrayObject *(__pyx_t_double_complex *, long, long, long, long)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "ndarray_complex_double_F", (void (**)(void))&__pyx_api_f_7eigency_11conversions_ndarray_complex_double_F, "PyArrayObject *(__pyx_t_double_complex *, long, long, long, long)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "ndarray_copy_complex_double_C", (void (**)(void))&__pyx_api_f_7eigency_11conversions_ndarray_copy_complex_double_C, "PyArrayObject *(__pyx_t_double_complex const *, long, long, long, long)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "ndarray_copy_complex_double_F", (void (**)(void))&__pyx_api_f_7eigency_11conversions_ndarray_copy_complex_double_F, "PyArrayObject *(__pyx_t_double_complex const *, long, long, long, long)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "ndarray_complex_float_C", (void (**)(void))&__pyx_api_f_7eigency_11conversions_ndarray_complex_float_C, "PyArrayObject *(__pyx_t_float_complex *, long, long, long, long)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "ndarray_complex_float_F", (void (**)(void))&__pyx_api_f_7eigency_11conversions_ndarray_complex_float_F, "PyArrayObject *(__pyx_t_float_complex *, long, long, long, long)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "ndarray_copy_complex_float_C", (void (**)(void))&__pyx_api_f_7eigency_11conversions_ndarray_copy_complex_float_C, "PyArrayObject *(__pyx_t_float_complex const *, long, long, long, long)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "ndarray_copy_complex_float_F", (void (**)(void))&__pyx_api_f_7eigency_11conversions_ndarray_copy_complex_float_F, "PyArrayObject *(__pyx_t_float_complex const *, long, long, long, long)") < 0) goto bad;
  Py_DECREF(module); module = 0;
  return 0;
  bad:
  Py_XDECREF(module);
  return -1;
}

#endif /* !__PYX_HAVE_API__eigency__conversions */
