// automatically generated by wrap
#include <wrap/matlab.h>
#include <folder/path/to/Test.h>
using namespace geometry;
typedef boost::shared_ptr<Test> SharedTest;
typedef boost::shared_ptr<Test> SharedTest;
typedef boost::shared_ptr<Test> Shared;
void mexFunction(int nargout, mxArray *out[], int nargin, const mxArray *in[])
{
  checkArguments("create_ptrs",nargout,nargin-1,0);
  Shared obj = unwrap_shared_ptr<Test>(in[0], "Test");
  pair< SharedTest, SharedTest > result = obj->create_ptrs();
  SharedTest* ret = new SharedTest(result.first);
  out[0] = wrap_collect_shared_ptr(ret,"Test");
  SharedTest* ret = new SharedTest(result.second);
  out[1] = wrap_collect_shared_ptr(ret,"Test");
}
