// automatically generated by wrap on 2011-Oct-31
#include <wrap/matlab.h>
#include <Test.h>
void mexFunction(int nargout, mxArray *out[], int nargin, const mxArray *in[])
{
  checkArguments("print",nargout,nargin-1,0);
  shared_ptr<Test> self = unwrap_shared_ptr< Test >(in[0],"Test");
  self->print();
}
