// automatically generated by wrap
#include <wrap/matlab.h>
#include <folder/path/to/Test.h>
using namespace geometry;
void mexFunction(int nargout, mxArray *out[], int nargin, const mxArray *in[])
{
  checkArguments("return_bool",nargout,nargin-1,1);
  boost::shared_ptr<Test> self = unwrap_shared_ptr< Test >(in[0],"Test");
  bool value = unwrap< bool >(in[1]);
  bool result = self->return_bool(value);
  out[0] = wrap< bool >(result);
}
