// automatically generated by wrap
#include <wrap/matlab.h>
#include <set>
#include <folder/path/to/Test.h>
using namespace geometry;
typedef boost::shared_ptr<Test> SharedTest;
typedef boost::shared_ptr<Test> Shared;
void mexFunction(int nargout, mxArray *out[], int nargin, const mxArray *in[])
{
  checkArguments("return_Test",nargout,nargin-1,1);
  mxArray* mxh = mxGetProperty(in[0],0,"self");
  Shared* self = *reinterpret_cast<Shared**> (mxGetPr(mxh));
  Shared obj = *self;
  boost::shared_ptr<Test> value = unwrap_shared_ptr< Test >(in[1], "Test");
  Test result = obj->return_Test(value);
  SharedTest* ret = new SharedTest(new Test(result));
  out[0] = wrap_collect_shared_ptr(ret,"Test");
}
