// automatically generated by wrap
#include <wrap/matlab.h>
#include <set>
#include <folder/path/to/Test.h>
using namespace geometry;
typedef boost::shared_ptr<Test> Shared;
void mexFunction(int nargout, mxArray *out[], int nargin, const mxArray *in[])
{
  checkArguments("return_matrix2",nargout,nargin-1,1);
  mxArray* mxh = mxGetProperty(in[0],0,"self");
  Shared* self = *reinterpret_cast<Shared**> (mxGetPr(mxh));
  Shared obj = *self;
      Matrix value = unwrap< Matrix >(in[1]);
  Matrix result = obj->return_matrix2(value);
  out[0] = wrap< Matrix >(result);
}
