// automatically generated by wrap on 2011-Dec-09
#include <wrap/matlab.h>
#include <folder/path/to/Test.h>
using namespace geometry;
void mexFunction(int nargout, mxArray *out[], int nargin, const mxArray *in[])
{
  checkArguments("return_Point2Ptr",nargout,nargin-1,1);
  shared_ptr<Test> self = unwrap_shared_ptr< Test >(in[0],"Test");
  bool value = unwrap< bool >(in[1]);
  shared_ptr<Point2> result = self->return_Point2Ptr(value);
  out[0] = wrap_shared_ptr(result,"Point2");
}
