// automatically generated by wrap
#include <wrap/matlab.h>
#include <set>
#include <Point2.h>
typedef boost::shared_ptr<Point2> Shared;
void mexFunction(int nargout, mxArray *out[], int nargin, const mxArray *in[])
{
  checkArguments("argChar",nargout,nargin-1,1);
  mxArray* mxh = mxGetProperty(in[0],0,"self");
  Shared* self = *reinterpret_cast<Shared**> (mxGetPr(mxh));
  Shared obj = *self;
      char a = unwrap< char >(in[1]);
  obj->argChar(a);
}
