// automatically generated by wrap
#include <wrap/matlab.h>
#include <set>
#include <Point2.h>
typedef boost::shared_ptr<VectorNotEigen> SharedVectorNotEigen;
typedef boost::shared_ptr<Point2> Shared;
void mexFunction(int nargout, mxArray *out[], int nargin, const mxArray *in[])
{
  checkArguments("vectorConfusion",nargout,nargin-1,0);
  mxArray* mxh = mxGetProperty(in[0],0,"self");
  Shared* self = *reinterpret_cast<Shared**> (mxGetPr(mxh));
  Shared obj = *self;
  VectorNotEigen result = obj->vectorConfusion();
  SharedVectorNotEigen* ret = new SharedVectorNotEigen(new VectorNotEigen(result));
  out[0] = wrap_collect_shared_ptr(ret,"VectorNotEigen");
}
