% automatically generated by wrap
classdef ClassD < handle
  properties
    self = 0
  end
  methods
    function obj = ClassD(varargin)
      if nargin == 2 && isa(varargin{1}, 'uint64') && varargin{1} == uint64(5139824614673773682)
        obj.self = varargin{2};
        testNamespaces_wrapper(obj.self);
      elseif nargin == 0
        obj.self = testNamespaces_wrapper(20);
      else
        error('Arguments do not match any overload of ClassD constructor');
      end
    end

    function delete(obj)
      testNamespaces_wrapper(21, obj.self);
    end

    function display(obj), obj.print(''); end

    function disp(obj), obj.display; end

  end

  methods(Static = true)
  end
end
