// automatically generated by wrap
#include <wrap/matlab.h>
#include <path/to/ns2.h>
#include <path/to/ns2/ClassA.h>
void mexFunction(int nargout, mxArray *out[], int nargin, const mxArray *in[])
{
  checkArguments("delete_ns2ClassA",nargout,nargin,1);
  delete_shared_ptr< ns2::ClassA >(in[0],"ns2ClassA");
}
