// automatically generated by wrap
#include <wrap/matlab.h>
#include <path/to/ns1.h>
#include <path/to/ns1/ClassB.h>
void mexFunction(int nargout, mxArray *out[], int nargin, const mxArray *in[])
{
  checkArguments("delete_ns1ClassB",nargout,nargin,1);
  delete_shared_ptr< ns1::ClassB >(in[0],"ns1ClassB");
}
