// automatically generated by wrap
#include <wrap/matlab.h>
#include <path/to/ns1.h>
void mexFunction(int nargout, mxArray *out[], int nargin, const mxArray *in[])
{
  checkArguments("delete_ns1ClassA",nargout,nargin,1);
  delete_shared_ptr< ns1::ClassA >(in[0],"ns1ClassA");
}
