// automatically generated by wrap
#include <wrap/matlab.h>
#include <path/to/ns2.h>
void mexFunction(int nargout, mxArray *out[], int nargin, const mxArray *in[])
{
  checkArguments("delete_ns2ClassC",nargout,nargin,1);
  delete_shared_ptr< ns2::ClassC >(in[0],"ns2ClassC");
}
