// automatically generated by wrap
#include <wrap/matlab.h>
#include <path/to/ns2.h>
#include <path/to/ns3.h>
void mexFunction(int nargout, mxArray *out[], int nargin, const mxArray *in[])
{
  checkArguments("delete_ns2ns3ClassB",nargout,nargin,1);
  delete_shared_ptr< ns2::ns3::ClassB >(in[0],"ns2ns3ClassB");
}
