// automatically generated by wrap
#include <wrap/matlab.h>
#include <ClassD.h>
void mexFunction(int nargout, mxArray *out[], int nargin, const mxArray *in[])
{
  checkArguments("delete_ClassD",nargout,nargin,1);
  delete_shared_ptr< ClassD >(in[0],"ClassD");
}
