// automatically generated by wrap on 2011-Dec-08
#include <wrap/matlab.h>
#include <ClassA.h>
void mexFunction(int nargout, mxArray *out[], int nargin, const mxArray *in[])
{
  checkArguments("new_ns1ClassA_",nargout,nargin,0);
  ns1::ClassA* self = new ns1::ClassA();
  out[0] = wrap_constructed(self,"ns1ClassA");
}
