// automatically generated by wrap on 2011-Dec-08
#include <wrap/matlab.h>
#include <ClassB.h>
void mexFunction(int nargout, mxArray *out[], int nargin, const mxArray *in[])
{
  checkArguments("new_ns2ns3ClassB_",nargout,nargin,0);
  ns2::ns3::ClassB* self = new ns2::ns3::ClassB();
  out[0] = wrap_constructed(self,"ns2ns3ClassB");
}
