// automatically generated by wrap
#include <wrap/matlab.h>
#include <ClassD.h>
void mexFunction(int nargout, mxArray *out[], int nargin, const mxArray *in[])
{
  checkArguments("new_ClassD_",nargout,nargin,0);
  ClassD* self = new ClassD();
  out[0] = wrap_constructed(self,"ClassD");
}
