// automatically generated by wrap on 2011-Dec-15
#include <wrap/matlab.h>
#include <path/to/ns2.h>
#include <path/to/ns2/ClassA.h>
void mexFunction(int nargout, mxArray *out[], int nargin, const mxArray *in[])
{
  checkArguments("new_ns2ClassA_",nargout,nargin,0);
  ns2::ClassA* self = new ns2::ClassA();
  out[0] = wrap_constructed(self,"ns2ClassA");
}
