// automatically generated by wrap
#include <wrap/matlab.h>
#include <set>
#include <path/to/ns2.h>
#include <path/to/ns2/ClassA.h>
typedef boost::shared_ptr<double> Shareddouble;
typedef boost::shared_ptr<ns2::ClassA> Shared;
void mexFunction(int nargout, mxArray *out[], int nargin, const mxArray *in[])
{
  checkArguments("ns2ClassA_afunction",nargout,nargin,0);
  double result = ns2::ClassA::afunction();
  out[0] = wrap< double >(result);
}
