name: Linux CI

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.name }} ${{ matrix.build_type }}
    runs-on: ${{ matrix.os }}

    env:
      CTEST_OUTPUT_ON_FAILURE: ON
      CTEST_PARALLEL_LEVEL: 2
      CMAKE_BUILD_TYPE: ${{ matrix.build_type }}
      GTSAM_BUILD_UNSTABLE: ${{ matrix.build_unstable }}
      BOOST_VERSION: 1.67.0

    strategy:
      fail-fast: true
      matrix:
        # Github Actions requires a single row to be added to the build matrix.
        # See https://help.github.com/en/articles/workflow-syntax-for-github-actions.
        name: [
          ubuntu-24.04-gcc-13,
          ubuntu-24.04-clang-16,
        ]

        build_type: [Debug, Release]
        build_unstable: [ON]
        include:
          - name: ubuntu-24.04-gcc-13
            os: ubuntu-24.04
            compiler: gcc
            version: "13"

          - name: ubuntu-24.04-clang-16
            os: ubuntu-24.04
            compiler: clang
            version: "16"

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install cmake build-essential pkg-config libpython3-dev python3-numpy libicu-dev

          if [ "${{ matrix.compiler }}" = "gcc" ]; then
            sudo apt-get install -y g++-${{ matrix.version }} g++-${{ matrix.version }}-multilib
            echo "CC=gcc-${{ matrix.version }}" >> $GITHUB_ENV
            echo "CXX=g++-${{ matrix.version }}" >> $GITHUB_ENV
          else
            sudo apt-get install -y clang-${{ matrix.version }} g++-multilib
            echo "CC=clang-${{ matrix.version }}" >> $GITHUB_ENV
            echo "CXX=clang++-${{ matrix.version }}" >> $GITHUB_ENV
          fi

      - name: Install Boost
        run: |
          bash .github/scripts/boost.sh

      - name: Build and Test
        run: bash .github/scripts/unix.sh -t
