name: Windows
on:
  pull_request:
    branches: 
      - "*" # Pull request for all branches
  schedule:
    - cron:  '10 12 * * 0'

# Every time you make a push to your PR, it cancel immediately the previous checks,
# and start a new one. The other runner will be available more quickly to your PR.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: vcpkg-windows-${{ matrix.type }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:      
        - type: x64
          BUILD_DIR: gtsam/3rdparty/vcpkg/cache
          VCPKG_ROOT: gtsam/3rdparty/vcpkg/cache/vcpkg
          VCPKG_LINK: https://github.com/microsoft/vcpkg/
          VCPKG_CONFIGS: gtsam/3rdparty/vcpkg
          BINARY_CACHE: gtsam/3rdparty/vcpkg/cache/windows
    env:
      BUILD_DIR: ${{ matrix.BUILD_DIR }}
      VCPKG_ROOT: ${{ matrix.VCPKG_ROOT }}
      VCPKG_LINK: ${{ matrix.VCPKG_LINK }}
      VCPKG_CONFIGS: ${{ matrix.VCPKG_CONFIGS }}
      BINARY_CACHE: ${{ matrix.BINARY_CACHE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Restore cache dependencies
        uses: actions/cache/restore@v3
        with:
          path: |
            ${{ matrix.BINARY_CACHE }}
          key: windows-${{ hashFiles('.github/workflows/windows.yml') }}
          restore-keys: windows-${{ hashFiles('.github/workflows/windows.yml') }}

      - name: Setup msbuild
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
          toolset: "29"

      - name: cl version
        shell: cmd
        run: |
          cl

      - uses: actions/setup-python@v4
        with:
          python-version: '3'

      - name: Install python packages
        if: success()
        shell: cmd
        run: |
          python --version
          python -m pip --version
          python -m pip install -r python/dev_requirements.txt

      - name: Install ninja
        if: success()
        shell: cmd
        run: |
          choco install ninja
          ninja --version
          where ninja

      - name: Init vcpkg
        if: success()
        shell: bash
        run: |
          mkdir -p $BUILD_DIR
          git -C $BUILD_DIR clone $VCPKG_LINK

      - name: Vcpkg build & cmake config
        if: success()
        shell: bash
        run: |
          export VCPKG_ROOT=${{ matrix.VCPKG_ROOT }}
          export VCPKG_BINARY_SOURCES="clear;files,${GITHUB_WORKSPACE}/${BINARY_CACHE},readwrite;"
          mkdir -p $BINARY_CACHE
          export CMAKE_GENERATOR=Ninja
          export CL=-openmp:experimental
          cmake . -B build \
              -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake \
              -DVCPKG_MANIFEST_DIR=$VCPKG_CONFIGS/manifest \
              -DVCPKG_INSTALLED_DIR=$VCPKG_ROOT/installed \
              -DVCPKG_OVERLAY_TRIPLETS=$VCPKG_CONFIGS/triplets \
              -DVCPKG_TARGET_TRIPLET=x64-windows-release \
              -DVCPKG_INSTALL_OPTIONS=--clean-after-build \
              -DCMAKE_BUILD_TYPE=Release \
              -DGTSAM_BUILD_EXAMPLES_ALWAYS=ON \
              -DGTSAM_ROT3_EXPMAP=ON \
              -DGTSAM_POSE3_EXPMAP=ON \
              -DGTSAM_BUILD_PYTHON=ON \
              -DGTSAM_BUILD_TESTS=ON \
              -DGTSAM_BUILD_UNSTABLE=OFF \
              -DGTSAM_USE_SYSTEM_EIGEN=ON \
              -DGTSAM_USE_SYSTEM_METIS=ON \
              -DGTSAM_SUPPORT_NESTED_DISSECTION=ON

      - name: Save cache dependencies
        id: cache-save
        uses: actions/cache/save@v3
        with:
          path: |
            ${{ matrix.BINARY_CACHE }}
          key: windows-${{ hashFiles('.github/workflows/windows.yml') }}-${{ hashFiles('gtsam\3rdparty\vcpkg\cache\vcpkg\installed\vcpkg\updates\*') }}

      - name: Cmake build
        shell: bash
        run: |
          cmake --build build --config Release -j 2

      - name: Run Python tests
        shell: bash
        run: |
          cmake --build build --target python-install
          cmake --build build --target python-test

      - name: Run tests
        shell: bash
        run: |
          # metis test are failing. remove this comment when fix it.
          # cmake --build build --target check -j 1
